// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.1
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xdeconv.h"

extern XDeconv_Config XDeconv_ConfigTable[];

XDeconv_Config *XDeconv_LookupConfig(u16 DeviceId) {
	XDeconv_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XDECONV_NUM_INSTANCES; Index++) {
		if (XDeconv_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XDeconv_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XDeconv_Initialize(XDeconv *InstancePtr, u16 DeviceId) {
	XDeconv_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XDeconv_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XDeconv_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

