#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("in_r_TDATA", 24, hls_in, 10, "axis", "in_data", 1),
	Port_Property("in_r_TVALID", 1, hls_in, 10, "axis", "in_vld", 1),
	Port_Property("in_r_TREADY", 1, hls_out, 10, "axis", "in_acc", 1),
	Port_Property("out_r_TDATA", 24, hls_out, 11, "axis", "out_data", 1),
	Port_Property("out_r_TVALID", 1, hls_out, 11, "axis", "out_vld", 1),
	Port_Property("out_r_TREADY", 1, hls_in, 11, "axis", "out_acc", 1),
	Port_Property("w_TDATA", 24, hls_in, 12, "axis", "in_data", 1),
	Port_Property("w_TVALID", 1, hls_in, 12, "axis", "in_vld", 1),
	Port_Property("w_TREADY", 1, hls_out, 12, "axis", "in_acc", 1),
	Port_Property("b_TDATA", 24, hls_in, 13, "axis", "in_data", 1),
	Port_Property("b_TVALID", 1, hls_in, 13, "axis", "in_vld", 1),
	Port_Property("b_TREADY", 1, hls_out, 13, "axis", "in_acc", 1),
	Port_Property("mean_TDATA", 24, hls_in, 14, "axis", "in_data", 1),
	Port_Property("mean_TVALID", 1, hls_in, 14, "axis", "in_vld", 1),
	Port_Property("mean_TREADY", 1, hls_out, 14, "axis", "in_acc", 1),
	Port_Property("std_TDATA", 24, hls_in, 15, "axis", "in_data", 1),
	Port_Property("std_TVALID", 1, hls_in, 15, "axis", "in_vld", 1),
	Port_Property("std_TREADY", 1, hls_out, 15, "axis", "in_acc", 1),
	Port_Property("s_axi_CTRL_BUS_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_AWADDR", 7, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_ARADDR", 7, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_CTRL_BUS_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
};
const char* HLS_Design_Meta::dut_name = "deconv";
